#!/bin/bash

# this script checks if an i3lock process is running.
# if there is one, kill all i3lock processes
# else, lock the screen
# adapting from this: https://stackoverflow.com/a/9118509/9063770

ps cax | grep i3lock > /dev/null
if [ $? -eq 0 ]; then
    killall i3lock

else
    notify-send "DUNST_COMMAND_PAUSE";
    $HOME/.config/i3/fancy-lock --blur=0x3
    sleep 1
    notify-send "DUNST_COMMAND_RESUME";
fi

exit 0
