#!/usr/bin/env bash
# www.jrodal.dev

pacman -Qqe > $HOME/packages.txt
/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME add $HOME/packages.txt
echo "packages.txt updated and added to commit"
